#!/bin/bash

Main() {
    echo "Session type: $XDG_SESSION_TYPE"
    local country=$(show-location-info country)
    country=${country,,}  # to lowercase
    echo "Detected country: $country"

    case "$XDG_SESSION_TYPE" in
        x11)
            case "$country" in
                us | gb | fr | it | es | de | fi | jp | cn | se)
                    echo "Setting keymap: $country"
                    setxkbmap "$country"
                    ;;
                *)
                    echo "Country '$country' not handled, falling back to 'us'"
                    setxkbmap us
                    ;;
            esac
            ;;
        wayland)
            echo "Wayland not supported"
            ;;
    esac
}

Main "$@"
