#!/bin/bash

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
DIE()     { echo2 "$progname: error: $1"; exit 1; }

Usage() {
    cat <<EOF >&2
$progname sends the input (stdin) to a pastebin service.

Usage: $progname [options]
Options:
   --0x0         Uses 0x0.st
   --dpaste      Uses dpaste.com
   --termbin     Uses termbin.com
   --help, -h    This help
Without options the services are tried in order until one succeeds or all fail.
Trial order: 0x0 dpaste termbin.
EOF
    [ "$1" ] && exit "$1"
}

0x0()         { $curl -F'file=@-' https://0x0.st ; }
dpaste()      { $curl -F "content=<-" https://dpaste.com/api/v2/ ; }
termbin()     { [ -x /bin/nc ] || return 1; nc -w $timeout termbin.com 9999; }
ix.io()       { $curl -F'f:1=<-'  ix.io ; }                            # 2023/12/04: fails??
wgetpaste()   { wgetpaste -n anonymous ; }                             # 2023/12/04: fails, no more maintained??

Tee() {
    local srv="$1"
    echo "$input" | "$srv" > $log
    return $?
}

Main() {
    local -r progname="${0##*/}"
    local -r log=/tmp/tmp.$progname.log
    local -r timeout=10                               # max seconds to wait when sending to pastebin
    local -r curl="/bin/curl --fail -Lsm $timeout"
    local count=0
    local services=()

    while true ; do
        case "$1" in
            --0x0 | --dpaste | --termbin)  services+=("${1:2}"); break ;;
            --help | -h)                   Usage 0 ;;
            -*)                            echo2 "Unsupported option '$1'"; exit 1 ;;
            *) services=(
                     0x0
                     dpaste
                     termbin
                 )
               break
               ;;
        esac
        shift
    done

    local -r input=$(cat)
    [ "$input" ] || DIE "No input!"

    for srv in "${services[@]}" ; do
        if Tee "$srv" ; then
            cat $log
            return 0
        fi
        ((count++))
        [ $count -lt ${#services[@]} ] && echo2 "==> Info: ${srv} failed, trying ${services[$count]} ..."
    done
    DIE "configured pastebin services failed!"
}

Main "$@"
