#!/bin/bash

# Like the "old" eos-sendlog, but can also take the command as parameter.
# The command from parameters will output in English.
#
# Tip: multiple commands (including parameters) can be given too:
#    eos-sendlog bash -c "command1 ; command2 ; command3"
#
# Tip2: user can select the pastebin provider (see 'eos-sendlog-helper -h'):
#    echo foobar | eos-sendlog --termbin

Main() {
    if [ "$1" ] ; then
        LANG=C "$@" | eos-sendlog-helper
    else
        eos-sendlog-helper "$@"    # $@ = options for eos-sendlog-helper
    fi
}

Main "$@"
