#!/bin/bash

DoNotify() {
    local cmd=(
        eos_notification_all       # function to notify all users

        system-reboot              # icon
        critical                   # urgency
        0                          # expire time (not used!)
        eos-reboot-required2       # appname
        "Reboot recommended!"      # title:
        "Reboot is recommended due to the upgrade of core system package(s)."        # message:
        RED                        # message color
    )
    "${cmd[@]}"
}

Wait-for-some-processes() {
    # Wait for all pacman-like processes to finish.

    systemctl disable --now eos-reboot-required.timer
    sleep 1
    source /usr/share/endeavouros/scripts/eos-script-lib-yad --limit-icons || return
    while ps -C pacman,yay,paru,makepkg >/dev/null ; do
        sleep 1
    done
    DoNotify
}

Wait-for-some-processes "$@"
