#!/bin/bash

echo2() { echo -e "$@" >&2 ; }
WARN()  { echo2 "$progname: warning: $1" ; }
echo2green() { echo2 "${GREEN}$1${RESET}" ; }

Main()
{
    local -r progname=${0##*/}
    local arg
    local do_sync=no

    local -r RED=$'\e[0;91m'
    local -r GREEN=$'\e[0;92m'
    local -r BLUE=$'\e[0;94m'
    local -r MAGENTA=$'\e[0;95m'
    local -r RESET=$'\e[0m'

    for arg in "$@" ; do
        case "$arg" in
            --flatpak)
                if [ -x /bin/flatpak ] ; then
                    echo2green "Updating flatpak apps..."
                    flatpak update
                    do_sync=yes
                else
                    WARN "package 'flatpak' is not installed"
                fi
                ;;
        esac
    done
    [ $do_sync = yes ] && sync
}

Main "$@"
